# Generated by Django 4.2.6 on 2023-10-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile_rename_author_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='username',
        ),
    ]
