# Generated by Django 4.2.6 on 2023-10-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_user_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
